version: 2
jobs:
  orangepi-plus2:
    docker:
      - image: docker:18.06.0-ce-git
    working_directory: $GOPATH/src/github.com/skycoin/libskycoin
    environment:
      QEMU_PLATFORM: orangepi-plus2

    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker build  --build-arg QEMU_PLATFORM --build-arg QEMU_OS=ubuntu --file $GOPATH/src/github.com/skycoin/libskycoin/docker/images/test-arm/Dockerfile  $GOPATH/src/github.com/skycoin/libskycoin -t skydev-test

  raspberrypi3:
    docker:
      - image: docker:18.06.0-ce-git
    working_directory: $GOPATH/src/github.com/skycoin/libskycoin
    environment:
      QEMU_PLATFORM: raspberrypi3

    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker build  --build-arg QEMU_PLATFORM --build-arg QEMU_OS=ubuntu --file $GOPATH/src/github.com/skycoin/libskycoin/docker/images/test-arm/Dockerfile  $GOPATH/src/github.com/skycoin/libskycoin -t skydev-test

  raspberrypi2:
    docker:
      - image: docker:18.06.0-ce-git
    working_directory: $GOPATH/src/github.com/skycoin/libskycoin
    environment:
      QEMU_PLATFORM: raspberry-pi2

    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker build  --build-arg QEMU_PLATFORM --build-arg QEMU_OS=ubuntu --file $GOPATH/src/github.com/skycoin/libskycoin/docker/images/test-arm/Dockerfile  $GOPATH/src/github.com/skycoin/libskycoin -t skydev-test

  bananapi_m1_plus:
    docker:
      - image: docker:18.06.0-ce-git
    working_directory: $GOPATH/src/github.com/skycoin/libskycoin
    environment:
      QEMU_PLATFORM: bananapi-m1-plus

    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker build  --build-arg QEMU_PLATFORM --build-arg QEMU_OS=ubuntu --file $GOPATH/src/github.com/skycoin/libskycoin/docker/images/test-arm/Dockerfile  $GOPATH/src/github.com/skycoin/libskycoin -t skydev-test

  publish-github-release_32:
    docker:
      - image: docker:18.06.0-ce-git
    working_directory: $GOPATH/src/github.com/skycoin/libskycoin
    environment:
      CIRCLE_TAG: $(git tag -l --points-at HEAD)
    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: if [[ $CIRCLE_TAG ]]; then docker build  --build-arg SHA1=$CIRCLE_SHA1 --build-arg GITHUB_OAUTH_TOKEN --build-arg PROJECT_USERNAME=$CIRCLE_PROJECT_USERNAME --build-arg PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME --build-arg QEMU_PLATFORM=raspberrypi3 --build-arg VERSION  --file $GOPATH/src/github.com/skycoin/libskycoin/docker/images/deploy-arm/Dockerfile  $GOPATH/src/github.com/skycoin/libskycoin -t skydev-deploy ; fi

workflows:
  version: 2
  arm_test:
    jobs:
      - publish-github-release_32
